name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecs update-service --cluster gamevault-cluster --service gamevault-service --force-new-deployment
      - name: Health Check
        run: |
          sleep 60
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://gamevault-service:5000/health)
          if [ "$STATUS" != "200" ]; then
            echo "Deployment failed, rolling back..."
            aws ecs update-service --cluster gamevault-cluster --service gamevault-service --task-definition gamevault-task-backup
            exit 1
          fi
      - name: Backup Task Definition
        run: |
          aws ecs register-task-definition --family gamevault-task-backup --container-definitions file://task-definition.json